runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/home.html
  upload: static/home.html
- url: /js/jquery.min.js
  static_files: static/jquery-1.11.0.min.js
  upload: static/jquery-1.11.0.min.js
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: _go_app
